added sorting landing page
miracle09110/concept-visualizer pull request #5
Opened 2024-05-07 21:52 UTC by adrian-taay

![sorting landing page](https://github.com/miracle09110/concept-visualizer/assets/155863617/080e2349-88c3-4719-9c9f-a3fc70dfe4d9)

for further revisions in design once all components are in place.

2024-05-08 08:23 UTC, miracle09110 requested changes
please see review

2024-05-08 08:23 UTC, miracle09110 commented on public/akshar-dave-lXIpMj1AFUI-unsplash.jpg
can you rename this file to something more readable

2024-05-08 08:23 UTC, miracle09110 commented on src/pages/sorting/Cards.css
> +.card {
if we're gonna use raw CSS, can you please use module.

Just rename this file to `cards.module.css`

then import on the jsx file

```
import style from "./cards.module.css"
```

example like what james did

https://github.com/miracle09110/concept-visualizer/blob/1ad610bc087631e53d388f2f5f9baf2afb1d7d71/src/pages/landingPage/explore/Explore.view.jsx

2024-05-08 08:23 UTC, miracle09110 commented on src/pages/sorting/Cards.jsx
> +import "./Cards.css";
please use module style for importing css.

Can we also separate each component to a folder. Like
```
Cards
   -> Cards.jsx
   -> cards.module.css
SortingPage
    -> SortingPage.jsx
    -> sortingPage.module.css
```

2024-05-08 08:23 UTC, miracle09110 commented on src/pages/sorting/Cards.jsx
Move this component to `component` folder, since it is not a page

2024-05-08 08:23 UTC, miracle09110 commented on src/pages/sorting/Cards.jsx
> +import "./Cards.css";
Also please use `.view.jsx` for this file to make it Cards.view.jsx`

2024-05-08 08:23 UTC, miracle09110 commented on src/pages/sorting/Cards.jsx
> +export default Cards;
Sorry a lot of comments, expected format should be like this
```
src
   components
      Cards
          Cards.view.jsx
          cards.module.css
    pages
       SortingPage
           SortingPage.view.jsx
            sortingpage.module.css
```

2024-05-09 08:42 UTC, miracle09110 commented on public/selection-sort.png
this image doesn't seem to be used this PR, can we remove?

2024-05-14 12:39 UTC, adrian-taay commented
![2024-05-14_20-38](https://github.com/miracle09110/concept-visualizer/assets/155863617/5beda09c-1adb-4ac9-8d54-a100d95c1800)

subject for changes in design

2024-05-15 03:39 UTC, miracle09110 approved these changes, later dismissed

2024-05-15 10:21 UTC, miracle09110 approved these changes, later dismissed

2024-05-15 10:22 UTC, miracle09110 approved these changes

2024-05-15 10:22 UTC, miracle09110 approved these changes

2024-05-15 10:22 UTC, merged